// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.CoffeeView = (function(_super) {

    __extends(CoffeeView, _super);

    function CoffeeView() {
      CoffeeView.__super__.constructor.apply(this, arguments);
      this.listenTo(this.model, "test", this.callback);
    }

    CoffeeView.prototype.callback = function() {
      return this.model.trigger("done");
    };

    return CoffeeView;

  })(Backbone.ViewMaster);

}).call(this);
